### PR TITLE
[Member] Add amino19

### PR DESCRIPTION
**Pull request by amino19**
Mentioned GitHub handle over your attendee sheet, add me to github-craftwork network. <3

### CODE REVIEW

**Comment by amino19** [comment]
@nayakastha GitHub action failing, Pl verify the error!

**Comment by nayakastha** [comment]
Hey @amino19! the GitHub action seems to be broken, but for starters, there is merge conflict, you can clear that first.

**Comment by amino19** [comment]
I resolved the conflicts, but again the same error came..

**Review by nayakastha — APPROVED** [review]

**Comment by nayakastha** [comment]
again I am not sure, will look into it sure

**Pull request merged**
